In [67]:
import pandas as pd
import numpy as np
from sklearn import cross_validation
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
from sklearn.cross_validation import train_test_split
from sklearn.metrics import log_loss

In [68]:
def generateBreedFeatures(data):
    l1=['American Hairless Terrier','American Leopard Hound','Appenzeller Sennenhunde','Azawakh','Barbet',
        'Basset Fauve de Bretagne','Belgian Laekenois','Biewer Terrier','Bolognese','Bracco Italiano',
        'Braque du Bourbonnais','Broholmer','Catahoula Leopard Dog','Caucasian Ovcharka','Central Asian Shepherd Dog',
        'Czechoslovakian Vlcak','Danish-Swedish Farmdog','Deutscher Wachtelhund','Dogo Argentino',
        'Drentsche Patrijshond','Drever','Dutch Shepherd','Estrela Mountain Dog','Eurasier','French Spaniel',
        'German Longhaired Pointer','German Spitz','Grand Basset Griffon Vendeen','Hamiltonstovare','Hovawart',
        'Jagdterrier','Jindo','Kai Ken','Karelian Bear Dog','Kishu Ken','Kromfohrlander','Lancashire Heeler',
        'Mudi','Nederlandse Kooikerhondje','Norrbottenspets','Perro de Presa Canario','Peruvian Inca Orchid',
        'Portuguese Podengo','Portuguese Pointer','Portuguese Sheepdog','Pumi','Pyrenean Mastiff',
        'Rafeiro do Alentejo','Russian Toy','Russian Tsvetnaya Bolonka','Schapendoes','Shikoku',
        'Slovensky Cuvac','Slovensky Kopov','Sloughi','Small Munsterlander Pointer','Spanish Mastiff',
        'Stabyhoun','Swedish Lapphund','Thai Ridgeback','Tornjak','Tosa','Transylvanian Hound',
        'Treeing Tennessee Brindle','Working Kelpie','Australian Cattle Dog','Australian Shepherd',
        'Bearded Collie','Beauceron','Belgian Malinois','Belgian Sheepdog','Belgian Tervuren','Bergamasco',
        'Berger Picard','Border Collie','Bouvier des Flandres','Briard','Canaan Dog','Cardigan Welsh Corgi',
        'Collie','Entlebucher Mountain Dog','Finnish Lapphund','German Shepherd Dog','Icelandic Sheepdog',
        'Miniature American Shepherd','Norwegian Buhund','Old English Sheepdog','Pembroke Welsh Corgi',
        'Polish Lowland Sheepdog','Puli','Pyrenean Shepherd','Shetland Sheepdog','Spanish Water Dog',
        'Swedish Vallhund','Afghan Hound','American English Coonhound','American Foxhound','Basenji',
        'Basset Hound','Beagle','Black and Tan Coonhound','Bloodhound','Bluetick Coonhound','Borzoi',
        'Cirneco de l etna','Dachshund','English Foxhound','Greyhound','Harrier','Ibizan Hound','Irish Wolfhound',
        'Norwegian Elkhound','Otterhound','Petit Basset Griffon Vendeen','Pharaoh Hound','Plott',
        'Portuguese Podengo Pequeno','Redbone Coonhound','Rhodesian Ridgeback','Saluki','Scottish Deerhound',
        'Treeing Walker Coonhound','Whippet','American Eskimo Dog','Bichon Frise','Boston Terrier','Bulldog',
        'Chinese Shar-Pei','Chow Chow','Coton de Tulear','Dalmatian','Finnish Spitz','French Bulldog','Keeshond',
        'Lhasa Apso','Lowchen','Norwegian Lundehund','Poodle','Schipperke','Shiba Inu','Tibetan Spaniel',
        'Tibetan Terrier','Xoloitzcuintli','American Water Spaniel','Boykin Spaniel','Brittany',
        'Chesapeake Bay Retriever','Clumber Spaniel','Cocker Spaniel','Curly-Coated Retriever',
        'English Cocker Spaniel','English Setter','English Springer Spaniel','Field Spaniel',
        'Flat-Coated Retriever','German Shorthaired Pointer','German Wirehaired Pointer','Golden Retriever',
        'Gordon Setter','Irish Red and White Setter','Irish Setter','Irish Water Spaniel','Labrador Retriever',
        'Lagotto Romagnolo','Nova Scotia Duck Tolling Retriever','Pointer','Spinone Italiano','Sussex Spaniel',
        'Vizsla','Weimaraner','Welsh Springer Spaniel','Wirehaired Pointing Griffon','Wirehaired Vizsla',
        'Airedale Terrier','American Staffordshire Terrier','Australian Terrier','Bedlington Terrier',
        'Border Terrier','Bull Terrier','Cairn Terrier','Cesky Terrier','Dandie Dinmont Terrier',
        'Glen of Imaal Terrier','Irish Terrier','Kerry Blue Terrier','Lakeland Terrier','Manchester Terrier',
        'Miniature Bull Terrier','Miniature Schnauzer','Norfolk Terrier','Norwich Terrier','Parson Russell Terrier',
        'Rat Terrier','Russell Terrier','Scottish Terrier','Sealyham Terrier','Skye Terrier','Smooth Fox Terrier',
        'Soft Coated Wheaten Terrier','Staffordshire Bull Terrier','Welsh Terrier','West Highland White Terrier',
        'Wire Fox Terrier','Affenpinscher','Brussels Griffon','Cavalier King Charles Spaniel','Chihuahua',
        'Chinese Crested','English Toy Spaniel','Havanese','Italian Greyhound','Japanese Chin','Maltese',
        'Miniature Pinscher','Papillon','Pekingese','Pomeranian','Pug','Shih Tzu','Silky Terrier','Toy Fox Terrier',
        'Yorkshire Terrier','Akita','Alaskan Malamute','Anatolian Shepherd Dog','Bernese Mountain Dog',
        'Black Russian Terrier','Boerboel','Boxer','Bullmastiff','Cane Corso','Chinook','Doberman Pinscher',
        'Dogue de Bordeaux','German Pinscher','Giant Schnauzer','Great Dane','Great Pyrenees',
        'Greater Swiss Mountain Dog','Komondor','Kuvasz','Leonberger','Mastiff','Neapolitan Mastiff','Newfoundland',
        'Portuguese Water Dog','Rottweiler','Samoyed','Siberian Husky','Standard Schnauzer','Tibetan Mastiff',
        'St. Bernard']
    l2=['FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS',
        'FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS',
        'FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS',
        'FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','FSS','Herding','Herding','Herding','Herding',
        'Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding',
        'Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding','Herding',
        'Herding','Herding','Herding','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound',
        'Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound','Hound',
        'Hound','Hound','Hound','Hound','Hound','Hound','Non_sporting','Non_sporting','Non_sporting','Non_sporting',
        'Non_sporting','Non_sporting','Non_sporting','Non_sporting','Non_sporting','Non_sporting','Non_sporting',
        'Non_sporting','Non_sporting','Non_sporting','Non_sporting','Non_sporting','Non_sporting','Non_sporting',
        'Non_sporting','Non_sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting',
        'Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting',
        'Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting','Sporting',
        'Sporting','Sporting','Sporting','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier',
        'Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier',
        'Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier','Terrier',
        'Terrier','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy','Toy',
        'Toy','Toy','Toy','Working','Working','Working','Working','Working','Working','Working','Working','Working',
        'Working','Working','Working','Working','Working','Working','Working','Working','Working','Working','Working',
        'Working','Working','Working','Working','Working','Working','Working','Working','Working','Working']
    
    l3=pd.DataFrame(l1)
    l3['breed1']=pd.DataFrame(l1)
    l3['group']=pd.DataFrame(l2)
    l3.drop(0,axis=1,inplace=True)
    l3['breed1']=l3['breed1'].str.upper()
    
    data=pd.merge(data, l3, on = 'breed1',how='left')
    
    l1=['Akita','Alaskan Malamute','Anatolian Shepherd Dog','Argentine Dogo','Beauceron','Bernese Mountain Dog',
        'Black Russian Terrier','Bloodhound','Borzoi','Bouvier des Flandres','Briard','Bullmastiff','Cane Corso',
        'Caucasian Ovcharka','Central Asian Shepherd Dog','Curly-Coated Retriever','Doberman Pinsch','Greyhound',
        'Otterhounds','Spinone Italiano','Afghan Hound','Airedale Terrier','American Foxhound',
        'American Staffordshire Terrier','Appenzeller Sennenhunde','Belgian Sheepdog','Belgian Tervuren',
        'Bergamasco','Black and Tan Coonhound','Bluetick Coonhound','Boxer','Bracco Italiano','Catahoula Leopard',
        'Chesapeake Bay Retriever','Chinook','Clumber Spaniel','English Setter','Flat Coat Retriever',
        'German Shorthaired Pointer','German Wirehaired Pointer','Golden Retrievers','Gordon Setters',
        'Irish Red and White Setters','Irish Setters','Labrador Retriever','The Standard Poodle','Redbone Coonhound',
        'Thai Ridgeback','Weimaraner','American English Coonhound','Australian Shepherd','Azawakh','Basset Hound',
        'Bearded Collie','Belgian Laekenois','Belgian Malinois','Bull Terrier','Bulldog','Chinese Sharpei',
        'Chow Chow','Collie','Dalmatian','English Springer Spaniel','Entlebucher Mountain Dog','Field Spaniel',
        'Finnish Lapphund','Grand Basset Griffon Vendéen','Harrier','Ibizan Hounds','Irish Water Spaniels',
        'Keeshond','Norwegian Elkhound','Nova Scotia Duck Tolling Retriever','The Pharaoh Hound','The Plott',
        'The Pointer','Portuguese Podengo','The Saluki','Samoyed','Siberian Husky','Sloughis','Stabyhouns',
        'Sussex Spaniel','Treeing Walker Coonhound','Vizslas','Wirehaired Pointing Griffon','Basenji','Beagle',
        'Cardigan Welsh Corgi','Cocker Spaniel','Dandie Dinmont Terrier','English Cocker Spaniel','Finnish Spitz',
        'German Pinscher','Kai Kens','Kerry Blue Terriers','Miniature Bull Terrier','Norwegian Buhunds',
        'Pembroke Welsh Corgi','Petit Bassett Griffon Vendeen','Polish Lowland Sheepdog','Portuguese Podengo (Medio)',
        'Portuguese Water Dog','Pyrenean Shepherd','Sealyham Terrier','Shetland Sheepdog','Skye Terrier',
        'Soft Coated Wheaten Terrier','Spanish Water Dogs','Staffordshire Bull Terrier','Standard Schnauzer',
        'Tibetan Terrier','Treeing Tennessee Brindle','Welsh Springer Spaniel','West Highland White Terrier',
        'Whippet','Wire Fox Terrier','Affenpinscher','American Eskimo','Miniature American Eskimo',
        'Toy American Eskimo','Australian Terrier','Bichon Frise','Bolognese','Border Terrier','Boston Terrier',
        'Brussels Griffon','Cairn Terrier','Cavalier King Charles Spaniel','Cesky Terrier','Chihuahua',
        'Chinese Crested','Coton de Tulear','Dachshund','English Toy Spaniel','French Bulldog','Havanese',
        'Italian Greyhound','Japanese Chin','Lancashire Heeler','Lhasa Apso','Lowchen','Maltese','Manchester Terrier',
        'Standard Manchester Terrier','Toy Manchester Terrier','Miniature Pinscher','Miniature Schnauzer',
        'Norfolk Terrier','Norwich Terrier','Papillon','Parson Russell Terrier','Pekingese','Pomeranian','Poodle',
        'Miniature Poodle','Toy Poodle','Portuguese Podengo (Pequeno)','Pug','Rat Terrier','Schipperke',
        'Scottish Terrier','Shiba Inu','Shih Tzu','Silky Terrier','Smooth Fox Terrier','Tibetan Spaniel',
        'Toy Fox Terrier','Yorkshire Terrier','Xoloitzcuintli']

    l2=['Large','Large','Large','Large','Large','Large','Large','Large','Large','Large','Large','Large','Large',
        'Large','Large','Large','Large','Large','Large','Medium Large','Medium Large','Medium Large','Medium Large',
        'Medium Large','Medium Large','Medium Large','Medium Large','Medium Large','Medium Large','Medium Large',
        'Medium Large','Medium Large','Medium Large','Medium Large','Medium Large','Medium Large','Medium Large',
        'Medium Large','Medium Large','Medium Large','Medium Large','Medium Large','Medium Large','Medium Large',
        'Medium Large','Medium Large','Medium Large','Medium Large','Medium','Medium','Medium','Medium','Medium',
        'Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium',
        'Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium',
        'Medium','Medium','Medium','Medium','Medium','Medium','Medium','Medium','Small Medium','Small Medium',
        'Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium',
        'Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium',
        'Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium',
        'Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium','Small Medium',
        'Small Medium','Small Medium','Small','Small','Small','Small','Small','Small','Small','Small','Small',
        'Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small',
        'Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small',
        'Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small','Small',
        'Small','Small','Small','Small','Small']
    
    l3=pd.DataFrame(l1)
    l3['breed1']=pd.DataFrame(l1)
    l3['size']=pd.DataFrame(l2)
    l3.drop(0,axis=1,inplace=True)
    l3['breed1']=l3['breed1'].str.upper()
    
    data=pd.merge(data, l3, on = 'breed1',how='left')
    '''
    #dangerous dogs
    l1=['Dalmatian','Great Dane','Presa Canario','Doberman Pinsch','Chow Chow','Alaskan Malamute','Wolf-Dog Hybrid',
        'German Shepherd','Rottweiler','Pit Bull']
    l2=['Dangerous Dog','Dangerous Dog','Dangerous Dog','Dangerous Dog','Dangerous Dog','Dangerous Dog',
        'Dangerous Dog','Dangerous Dog','Dangerous Dog','Dangerous Dog']
    
    l3=pd.DataFrame(l1)
    l3['breed1']=pd.DataFrame(l1)
    l3['dangerous']=pd.DataFrame(l2)
    l3.drop(0,axis=1,inplace=True)
    l3['breed1']=l3['breed1'].str.upper()
    
    data=pd.merge(data, l3, on = 'breed1',how='left')
    
    ####Smart
    l1=['Bloodhound','Border Collie','Doberman Pinscher','German Shepherd Dog','Golden Retriever',
        'Labrador Retriever','Papillon','Poodle','Rottweiler','Shetland Sheepdog']
    l2=['Smart','Smart','Smart','Smart','Smart','Smart','Smart','Smart','Smart','Smart']
    
    l3=pd.DataFrame(l1)
    l3['breed1']=pd.DataFrame(l1)
    l3['smart']=pd.DataFrame(l2)
    l3.drop(0,axis=1,inplace=True)
    l3['breed1']=l3['breed1'].str.upper()
    
    data=pd.merge(data, l3, on = 'breed1',how='left')
    
    ####Kids
    l1=['Beagle','Boxer','Bull Terrier','Bulldog','Golden Retriever','Labrador Retriever','Newfoundland',
        'Soft Coated Wheaten Terrier','Weimaraner']
    l2=['Kids','Kids','Kids','Kids','Kids','Kids','Kids','Kids','Kids']
    
    l3=pd.DataFrame(l1)
    l3['breed1']=pd.DataFrame(l1)
    l3['kids']=pd.DataFrame(l2)
    l3.drop(0,axis=1,inplace=True)
    l3['breed1']=l3['breed1'].str.upper()
    
    data=pd.merge(data, l3, on = 'breed1',how='left')
    
    ####Hypo
    l1=['Afghan Hound','American Hairless Terrier','Bedlington Terrier','Bichon Frise','Chinese Crested',
        'Coton de Tulear','Giant Schnauzer','Irish Water Spaniel','Kerry Blue Terrier','Lagotto Romagnolo',
        'Maltese','Peruvian Inca Orchid','Poodle','Portuguese Water Dog','Soft Coated Wheaten Terrier',
        'Standard Schnauzer','Xoloitzcuintli']
    l2=['Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic',
        'Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic',
        'Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic','Hypoallergenic']
    
    l3=pd.DataFrame(l1)
    l3['breed1']=pd.DataFrame(l1)
    l3['hypo']=pd.DataFrame(l2)
    l3.drop(0,axis=1,inplace=True)
    l3['breed1']=l3['breed1'].str.upper()
    
    data=pd.merge(data, l3, on = 'breed1',how='left')
    
    ####Family
    l1=['Beagle','Brussels Griffon','Bulldog','Collie','French Bulldog','Golden Retriever','Irish Setter',
        'Labrador Retriever','Newfoundland','Pug']
    l2=['Family','Family','Family','Family','Family','Family','Family','Family','Family','Family']
    
    l3=pd.DataFrame(l1)
    l3['breed1']=pd.DataFrame(l1)
    l3['family']=pd.DataFrame(l2)
    l3.drop(0,axis=1,inplace=True)
    l3['breed1']=l3['breed1'].str.upper()
    
    data=pd.merge(data, l3, on = 'breed1',how='left')
    '''
    return data

In [69]:
def getAge(x):
    if pd.notnull(x):
        value = int(x.split(' ')[0])
        if x.endswith('day') or x.endswith('days'):
            return value
        if x.endswith('weeks') or x.endswith('week'):
            return value*7
        if x.endswith('month') or x.endswith('months'):
            return value*30
        if x.endswith('year') or x.endswith('years'):
            return value*365
    return -1

def cleanBreed(x):
    x = x.replace('Mix','')
    x = x.replace('Shorthair','')
    x = x.replace('Medium Hair','')
    x = x.replace('Longhair','')
    x = x.replace('  ',' ')
    x = x.replace('   ',' ')
    x = x.replace('    ',' ')
    x = x.strip()
    
    return x

def cleanColor(x):
    x = x.replace('Tabby','')
    x = x.replace('  ',' ')
    x = x.replace('   ',' ')
    x = x.replace('    ',' ')
    x = x.strip()
    
    return x

def splitBreed(x, i):
    x = x.split('/')
    if len(x) >= (i+1):
        return x[i]
    return 'null'

def getHairType(x):
    if pd.notnull(x) and 'Shorthair' in x:
        return 1
    if pd.notnull(x) and 'Medium Hair' in x:
        return 2
    if pd.notnull(x) and 'Longhair' in x:
        return 3
    return -1

def getDayPeriod(x):
    if x.hour < 6:
        return 0
    if x.hour >= 6 and x.hour < 12:
        return 1
    if x.hour >= 12 and x.hour < 18:
        return 2
    if x.hour >= 18:
        return 3
    return -1

def getSeason(x):
    if 4<=x<=6:
        return 1
    if 7<=x<=9:
        return 2
    if 10<=x<=12:
        return 3
    else:
        return 0
    
def getHolidays(day, month):
    #confederate Heroes
    if month==1 and day==19:
        return 1
    #Texas Independance
    if month==3 and day==2:
        return 2
    #San Jacinto Day        
    if month==4 and day==21:
        return 3                  
    #Mothers Day        
    if month==5 and day==10:
        return 4              
    #Emancipation Day        
    if month==6 and day==19:
        return 5
    #Fathers Day        
    if month==6 and 18<=day<=22:
        return 6
    #Lyndon day       
    if month==8 and day==27:
        return 7
    #Veterans day       
    if month==11 and day==11:
        return 8
    #ThanksGiving                    
    if month==11 and 25<=day<=27:
        return 9
    #Christmas                    
    if month==12 and 23<=day<=27:
        return 10
    return 0

In [70]:
def mostRepresentativeBreeds(x):

    if x == "Shetland Sheepdog":
        return 1
    if x == "Pit Bull":
        return 2
    if x == "Lhasa Apso":
        return 3
    if x == "Chihuahua Shorthair":
        return 4
    return 0

In [71]:
def generate_features(data, train = False):
    if train:
        data.drop('OutcomeSubtype', axis=1, inplace=True)
        
    ###### RETIRANDO O OUTCOMESUBTYPE O NAME DO TREINO E TESTE ######
    data['has_name'] = data['Name'].apply(lambda x :  pd.notnull(x) )
    data.drop(['Name'], axis=1, inplace=True)
    
    #Date
    data['DateTime'] = data['DateTime'].apply(lambda x : pd.tslib.Timestamp(x, tz=None))
    data['day'] = data['DateTime'].apply(lambda x : x.day)
    data['month'] = data['DateTime'].apply(lambda x : x.month)
    data['year'] = data['DateTime'].apply(lambda x : x.year)
    data['hour'] = data['DateTime'].apply(lambda x : x.hour)
    data['minute'] = data['DateTime'].apply(lambda x : x.minute)
    data['day_of_week'] = data['DateTime'].apply(lambda x : x.weekday())
    data['weekday'] = data['DateTime'].apply(lambda x : x.weekday() < 5)
    data['working_hour'] = data['DateTime'].apply(lambda x : x.hour >= 8 and x.hour <= 18)
    data['madrugada'] = data['DateTime'].apply(lambda x : x.hour < 6)
    data['manha'] = data['DateTime'].apply(lambda x : x.hour >= 6 and x.hour < 12)
    data['tarde'] = data['DateTime'].apply(lambda x : x.hour >= 12 and x.hour < 18)
    data['noite'] = data['DateTime'].apply(lambda x : x.hour >= 18)
    #data['quarter'] = data['DateTime'].apply(lambda x : x.quarter)#<<<
    #data['weekofyear'] = data['DateTime'].apply(lambda x : x.weekofyear)#<<<
    #data['season'] = data['month'].apply(lambda x : getSeason(x))#<<<
    #data['holiday'] = data['DateTime'].apply(lambda x : getHolidays(x.day, x.month))#<<<
    '''
    data['day_period'] = data['DateTime'].apply(lambda x : getDayPeriod(x))
    '''
    data.drop(['DateTime'], axis=1, inplace=True)
    
    #Age
    data['age'] = data['AgeuponOutcome'].apply(lambda x : getAge(x))
    data['puppy'] = data['age'].apply(lambda x : x <= 365)
    data['adolescence'] = data['age'].apply(lambda x : x > 365 and x <= 730)
    data['adulthood'] = data['age'].apply(lambda x : x > 730 and x <= 2920)
    data['senior'] = data['age'].apply(lambda x : x > 2920)
    data.drop(['AgeuponOutcome'], axis=1, inplace=True)
    
    #Sex
    data['male'] = data['SexuponOutcome'].apply(lambda x : pd.notnull(x) and x.endswith('Male'))
    data['female'] = data['SexuponOutcome'].apply(lambda x : pd.notnull(x) and x.endswith('Female'))
    data['castrated'] = data['SexuponOutcome'].apply(lambda x : pd.notnull(x) and (x.startswith('Spayed') 
                                                                                   or x.startswith('Neutered')))
    data.drop(['SexuponOutcome'], axis=1, inplace=True)
    '''
    data['sex'] = data['SexuponOutcome'].apply(lambda x : 1 if pd.notnull(x) and x.endswith('Male') else 0)
    data['intact'] = data['SexuponOutcome'].apply(lambda x : pd.notnull(x) and x.startswith('Intact'))
    data['spayed'] = data['SexuponOutcome'].apply(lambda x : pd.notnull(x) and x.startswith('Spayed'))
    data['neutered'] = data['SexuponOutcome'].apply(lambda x : pd.notnull(x) and x.startswith('Neutered'))
    data.drop(['SexuponOutcome'], axis=1, inplace=True)
    '''
    
    #Breed
    
    data['mix'] = data['Breed'].apply(lambda x : pd.notnull(x) and x.endswith('Mix'))
    data['shorthair'] = data['Breed'].apply(lambda x : pd.notnull(x) and 'Shorthair' in x)
    data['mediumhair'] = data['Breed'].apply(lambda x : pd.notnull(x) and 'Medium Hair' in x)
    data['longhair'] = data['Breed'].apply(lambda x : pd.notnull(x) and 'Longhair' in x)
    '''
    data['mix'] = data['Breed'].apply(lambda x : pd.notnull(x) and x.endswith('Mix'))
    data['hair'] = data['Breed'].apply(lambda x : getHairType(x))
    '''
    data['Breed'] = data['Breed'].apply(lambda x : cleanBreed(x))
    data['breed1'] = data['Breed'].apply(lambda x : splitBreed(x, 0).upper())
    data['breed2'] = data['Breed'].apply(lambda x : splitBreed(x, 1).upper())
    data.drop(['Breed'], axis=1, inplace=True)
    data['specialBreeds'] = data['breed1'].apply(lambda x : mostRepresentativeBreeds(x))
    
    #Color
    data['tabby'] = data['Color'].apply(lambda x : pd.notnull(x) and 'Tabby' in x)
    data['Color'] = data['Color'].apply(lambda x : cleanColor(x))
    data['color1'] = data['Color'].apply(lambda x : splitBreed(x, 0))
    data['color2'] = data['Color'].apply(lambda x : splitBreed(x, 1))
    #data['unicolor'] = data['color2'].apply(lambda x : x == 'null')#<<<
    
    
    data.drop(['Color'], axis=1, inplace=True)

Lendo os arquivos do treino e test. <br />
Biblioteca utilizada: <br />
Pandas: http://pandas.pydata.org/<br />
Função utilizada: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

In [72]:
train = pd.read_csv('input/train.csv', index_col='AnimalID')
test = pd.read_csv('input/test.csv', index_col='ID')

In [73]:
def getValueFrequency(group, counts, outcomeType, date):
    try:
        g = group.xs((outcomeType, date), level=('OutcomeType', 'Date'))['DateTime']
    except:
        return 0
    if g.values.size > 0:
        val = g.values[0]
        return val/(counts[date] * 1.0)
    return 0

def setDate(x):
    x = x.date().replace(day=1)
    return x

def generateFrequencyFeatures(data, test):
    data['DateTime'] = data['DateTime'].apply(lambda x : pd.tslib.Timestamp(x, tz=None))
    data['Date'] = data['DateTime'].apply(lambda x : setDate(x))
    
    test['DateTime'] = test['DateTime'].apply(lambda x : pd.tslib.Timestamp(x, tz=None))
    test['Date'] = test['DateTime'].apply(lambda x : setDate(x))
    
    counts = data['Date'].value_counts()
    data['outcomes'] = data['Date'].apply(lambda x : counts[x]/(len(data) * 1.0))
    test['outcomes'] = test['Date'].apply(lambda x : counts[x]/(len(test) * 1.0))
    
    group = data.groupby(['Date', 'OutcomeType']).count()
    data['Transfer'] = data['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Transfer', x))
    test['Transfer'] = test['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Transfer', x))
    data['Return_to_owner'] = data['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Return_to_owner', x))
    test['Return_to_owner'] = test['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Return_to_owner', x))
    data['Euthanasia'] = data['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Euthanasia', x))
    test['Euthanasia'] = test['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Euthanasia', x))
    data['Adoption'] = data['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Adoption', x))
    test['Adoption'] = test['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Adoption', x))
    data['Died'] = data['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Died', x))
    test['Died'] = test['Date'].apply(lambda x,g=group,c=counts : getValueFrequency(g, c, 'Died', x))
    
    #data['outcomes'] = data['Date'].apply(lambda x : data[data['Date'] == x].size)
    #data.drop(['Date'], axis=1, inplace=True)
    #test.drop(['Date'], axis=1, inplace=True)

In [74]:
def getValueFrequency2(group, counts, outcomeType, breed):
    try:
        g = group.xs((outcomeType, breed), level=('OutcomeType', 'breed1'))['Date']
    except:
        return 0
    if g.values.size > 0:
        val = g.values[0]
        return val/(counts[breed] * 1.0)
    return 0



def generateFrequencyFeatures2(data, test):

    counts = data['breed1'].value_counts()
    
    group = data.groupby(['breed1', 'OutcomeType']).count()
    
    data['Transfer_breed'] = data['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Transfer', x))
    test['Transfer_breed'] = test['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Transfer', x))
    data['Return_to_owner_breed'] = data['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Return_to_owner', x))
    test['Return_to_owner_breed'] = test['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Return_to_owner', x))
    data['Euthanasia_breed'] = data['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Euthanasia', x))
    test['Euthanasia_breed'] = test['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Euthanasia', x))
    data['Adoption_breed'] = data['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Adoption', x))
    test['Adoption_breed'] = test['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Adoption', x))
    data['Died_breed'] = data['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Died', x))
    test['Died_breed'] = test['breed1'].apply(lambda x,g=group,c=counts : getValueFrequency2(g, c, 'Died', x))
    
    #data['outcomes'] = data['Date'].apply(lambda x : data[data['Date'] == x].size)
    #data.drop(['Date'], axis=1, inplace=True)
    #test.drop(['Date'], axis=1, inplace=True)

In [75]:
train.head()

Name             DateTime      OutcomeType OutcomeSubtype  \
AnimalID                                                                 
A671945   Hambone  2014-02-12 18:22:00  Return_to_owner            NaN   
A656520     Emily  2013-10-13 12:44:00       Euthanasia      Suffering   
A686464    Pearce  2015-01-31 12:28:00         Adoption         Foster   
A683430       NaN  2014-07-11 19:09:00         Transfer        Partner   
A667013       NaN  2013-11-15 12:52:00         Transfer        Partner   

         AnimalType SexuponOutcome AgeuponOutcome  \
AnimalID                                            
A671945         Dog  Neutered Male         1 year   
A656520         Cat  Spayed Female         1 year   
A686464         Dog  Neutered Male        2 years   
A683430         Cat    Intact Male        3 weeks   
A667013         Dog  Neutered Male        2 years   

                                Breed        Color  
AnimalID                                            
A671945         Shetland Sheepdog Mix  Brown/White  
A656520        Domestic Shorthair Mix  Cream Tabby  
A686464                  Pit Bull Mix   Blue/White  
A683430        Domestic Shorthair Mix   Blue Cream  
A667013   Lhasa Apso/Miniature Poodle          Tan

Removendo a coluna **OutcomeSubtype**, porque ela não existe no test. <br />
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html

In [76]:
generateFrequencyFeatures(train,test)
generate_features(train, True)
generate_features(test)
generateFrequencyFeatures2(train,test)
'''
train = generateBreedFeatures(train)
test = generateBreedFeatures(test)
'''

test.head()

AnimalType        Date  outcomes  Transfer  Return_to_owner  Euthanasia  \
ID                                                                           
1         Dog  2015-10-01  0.084497  0.388430         0.190083    0.036157   
2         Dog  2014-07-01  0.114176  0.371560         0.113150    0.061927   
3         Cat  2016-01-01  0.071840  0.268530         0.224787    0.025516   
4         Dog  2013-12-01  0.080744  0.318919         0.152432    0.065946   
5         Dog  2015-09-01  0.087814  0.386680         0.154076    0.042744   

    Adoption      Died has_name  day    ...              breed2  \
ID                                      ...                       
1   0.371901  0.013430     True   12    ...                NULL   
2   0.442661  0.010703     True   26    ...      SIBERIAN HUSKY   
3   0.476306  0.004860     True   13    ...                NULL   
4   0.461622  0.001081     True   28    ...                NULL   
5   0.408549  0.007952     True   24    ...                NULL   

    specialBreeds  tabby    color1  color2 Transfer_breed  \
ID                                                          
1               0  False       Red   White       0.247520   
2               0  False     Black     Tan       0.214286   
3               0   True     Brown    null       0.502843   
4               0  False  Tricolor    null       0.209302   
5               0  False     White    null       0.206452   

   Return_to_owner_breed Euthanasia_breed Adoption_breed Died_breed  
ID                                                                   
1               0.260052         0.042820       0.447520   0.002089  
2               0.286925         0.044794       0.450363   0.003632  
3               0.042209         0.064180       0.377469   0.013299  
4               0.186047         0.023256       0.581395   0.000000  
5               0.303226         0.035484       0.454839   0.000000  

[5 rows x 44 columns]

In [77]:
train.describe()

outcomes      Transfer  Return_to_owner    Euthanasia  \
count  26729.000000  26729.000000     26729.000000  26729.000000   
mean       0.035781      0.352501         0.179056      0.058177   
std        0.006677      0.057440         0.037622      0.015247   
min        0.020352      0.242647         0.113150      0.025516   
25%        0.031352      0.314248         0.149197      0.053422   
50%        0.035392      0.367206         0.176674      0.063126   
75%        0.039882      0.400705         0.220588      0.068815   
max        0.048936      0.455603         0.242898      0.081986   

           Adoption          Died           day         month          year  \
count  26729.000000  26729.000000  26729.000000  26729.000000  26729.000000   
mean       0.402896      0.007370     15.698343      6.925736   2014.430731   
std        0.053892      0.003660      8.770496      3.495869      0.741408   
min        0.274463      0.001081      1.000000      1.000000   2013.000000   
25%        0.358942      0.004521      8.000000      4.000000   2014.000000   
50%        0.408549      0.007692     16.000000      7.000000   2014.000000   
75%        0.442857      0.010703     23.000000     10.000000   2015.000000   
max        0.498162      0.014286     31.000000     12.000000   2016.000000   

               hour        minute   day_of_week           age  specialBreeds  \
count  26729.000000  26729.000000  26729.000000  26729.000000        26729.0   
mean      14.445396     27.681170      3.106364    793.595308            0.0   
std        3.337331     18.189427      2.046001   1082.662074            0.0   
min        0.000000      0.000000      0.000000     -1.000000            0.0   
25%       12.000000     12.000000      1.000000     60.000000            0.0   
50%       15.000000     27.000000      3.000000    365.000000            0.0   
75%       17.000000     43.000000      5.000000   1095.000000            0.0   
max       23.000000     59.000000      6.000000   7300.000000            0.0   

       Transfer_breed  Return_to_owner_breed  Euthanasia_breed  \
count    26729.000000           26729.000000      26729.000000   
mean         0.352501               0.179056          0.058177   
std          0.134405               0.129233          0.032803   
min          0.000000               0.000000          0.000000   
25%          0.243729               0.042209          0.042820   
50%          0.297674               0.206422          0.064180   
75%          0.502843               0.286925          0.064180   
max          1.000000               1.000000          0.500000   

       Adoption_breed    Died_breed  
count    26729.000000  26729.000000  
mean         0.402896      0.007370  
std          0.084725      0.006512  
min          0.000000      0.000000  
25%          0.377469      0.001957  
50%          0.377469      0.007493  
75%          0.447520      0.013299  
max          1.000000      0.090909

In [78]:
breed_train = np.append(train['breed1'], train['breed2'])
breed_test = np.append(test['breed1'], test['breed2'])
le = LabelEncoder().fit(np.append(breed_train, breed_test))
train['breed1'] = le.transform(train['breed1'])
test['breed1'] = le.transform(test['breed1'])
train['breed2'] = le.transform(train['breed2'])
test['breed2'] = le.transform(test['breed2'])

In [79]:
color_train = np.append(train['color1'], train['color2'])
color_test = np.append(test['color1'], test['color2'])
le = LabelEncoder().fit(np.append(color_train, color_test))
train['color1'] = le.transform(train['color1'])
test['color1'] = le.transform(test['color1'])
train['color2'] = le.transform(train['color2'])
test['color2'] = le.transform(test['color2'])

In [80]:
for col in ['AnimalType','Date']:
    le = LabelEncoder().fit(np.append(train[col], test[col]))
    train[col] = le.transform(train[col])
    test[col] = le.transform(test[col])

Convertendo campo categórico para número inteiro, porque os modelos matemáricos do sklearn só aceitam números. <br />
Utilizando: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.LabelEncoder.html

Separando o TARGET do meu treino.

In [81]:
target = train['OutcomeType']
data   = train.drop('OutcomeType', axis=1)

In [82]:
train.head()

OutcomeType  AnimalType  Date  outcomes  Transfer  \
AnimalID                                                          
A671945   Return_to_owner           1     4  0.024356  0.314900   
A656520        Euthanasia           0     0  0.036440  0.391170   
A686464          Adoption           1    15  0.028434  0.257895   
A683430          Transfer           0     9  0.048936  0.371560   
A667013          Transfer           1     1  0.030042  0.330012   

          Return_to_owner  Euthanasia  Adoption      Died has_name    ...      \
AnimalID                                                              ...       
A671945          0.213518    0.066052  0.400922  0.004608     True    ...       
A656520          0.152977    0.074949  0.368583  0.012320     True    ...       
A686464          0.223684    0.065789  0.447368  0.005263     True    ...       
A683430          0.113150    0.061927  0.442661  0.010703    False    ...       
A667013          0.179328    0.061021  0.425903  0.003736    False    ...       

          breed2  specialBreeds  tabby  color1  color2  Transfer_breed  \
AnimalID                                                                 
A671945      154              0  False      15      55        0.243243   
A656520      154              0   True      25      58        0.502843   
A686464      154              0  False       7      55        0.243729   
A683430      154              0  False       9      58        0.502843   
A667013      144              0  False      50      58        0.614286   

         Return_to_owner_breed Euthanasia_breed Adoption_breed Died_breed  
AnimalID                                                                   
A671945               0.378378         0.081081       0.297297   0.000000  
A656520               0.042209         0.064180       0.377469   0.013299  
A686464               0.320871         0.135826       0.295788   0.003786  
A683430               0.042209         0.064180       0.377469   0.013299  
A667013               0.271429         0.014286       0.085714   0.014286  

[5 rows x 45 columns]

Executando o método random forest classifier do sklearn.<br />
http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [83]:
target.head()
test.head()

AnimalType  Date  outcomes  Transfer  Return_to_owner  Euthanasia  \
ID                                                                      
1            1    24  0.084497  0.388430         0.190083    0.036157   
2            1     9  0.114176  0.371560         0.113150    0.061927   
3            0    27  0.071840  0.268530         0.224787    0.025516   
4            1     2  0.080744  0.318919         0.152432    0.065946   
5            1    23  0.087814  0.386680         0.154076    0.042744   

    Adoption      Died has_name  day    ...      breed2  specialBreeds  tabby  \
ID                                      ...                                     
1   0.371901  0.013430     True   12    ...         154              0  False   
2   0.442661  0.010703     True   26    ...         197              0  False   
3   0.476306  0.004860     True   13    ...         154              0   True   
4   0.461622  0.001081     True   28    ...         154              0  False   
5   0.408549  0.007952     True   24    ...         154              0  False   

    color1  color2 Transfer_breed Return_to_owner_breed Euthanasia_breed  \
ID                                                                         
1       41      55       0.247520              0.260052         0.042820   
2        2      50       0.214286              0.286925         0.044794   
3       15      58       0.502843              0.042209         0.064180   
4       54      58       0.209302              0.186047         0.023256   
5       55      58       0.206452              0.303226         0.035484   

   Adoption_breed Died_breed  
ID                            
1        0.447520   0.002089  
2        0.450363   0.003632  
3        0.377469   0.013299  
4        0.581395   0.000000  
5        0.454839   0.000000  

[5 rows x 44 columns]

In [84]:
clf = xgb.XGBClassifier(max_depth=10, n_estimators=175, learning_rate=0.05, silent=1, objective='multi:softprob',
                        subsample=0.55,colsample_bytree=0.65)
fit = clf.fit(data, target)
proba = fit.predict_proba(test)
print cross_validation.cross_val_score(clf, data, target, scoring='log_loss')

[-0.72396381 -0.72211103 -0.71715707]


In [64]:
'''for n in range(100, 450, 25):
    for d in range (2, 11, 1):
        clf = xgb.XGBClassifier(max_depth=d, n_estimators=n, learning_rate=0.05, silent=1, objective='multi:softprob',
                        subsample=0.55,colsample_bytree=0.65)
        fit = clf.fit(data, target)
        proba = fit.predict_proba(test)
        print '[n='+str(n)+' d='+str(d)+'] '+str(cross_validation.cross_val_score(clf, data, target, scoring='log_loss'))
'''

[n=100 d=2] [-0.83689628 -0.8283312  -0.82434193]
[n=100 d=3] [-0.80715529 -0.79665308 -0.79570285]
[n=100 d=4] [-0.78743215 -0.77728835 -0.775879  ]
[n=100 d=5] [-0.77447217 -0.76436393 -0.76240123]
[n=100 d=6] [-0.76382459 -0.75478933 -0.75283341]
[n=100 d=7] [-0.75579189 -0.74788492 -0.74550681]
[n=100 d=8] [-0.75032567 -0.74342676 -0.73998716]
[n=100 d=9] [-0.74589829 -0.74002025 -0.73505561]
[n=100 d=10] [-0.74262882 -0.7369784  -0.73211477]
[n=125 d=2] [-0.81801477 -0.80860395 -0.80604292]
[n=125 d=3] [-0.7904067  -0.77933786 -0.77981493]
[n=125 d=4] [-0.77216697 -0.76209774 -0.76152315]
[n=125 d=5] [-0.76020693 -0.75077311 -0.74964862]
[n=125 d=6] [-0.75071484 -0.74204119 -0.7399109 ]
[n=125 d=7] [-0.74330155 -0.73556973 -0.73321756]
[n=125 d=8] [-0.73867263 -0.73192538 -0.72806524]
[n=125 d=9] [-0.73410601 -0.72909497 -0.72436127]
[n=125 d=10] [-0.73171263 -0.72712343 -0.72135836]
[n=150 d=2] [-0.80575265 -0.79642054 -0.79479188]
[n=150 d=3] [-0.78058333 -0.76984909 -0.77015914

KeyboardInterrupt: 

In [ ]:
for s in np.arange(0,1,0.1):
    for cs in np.arange(0,1,0.1):
        clf = xgb.XGBClassifier(max_depth=10, n_estimators=175, learning_rate=0.05, silent=1, objective='multi:softprob',
                subsample=s,colsample_bytree=cs)
        fit = clf.fit(data, target)
        proba = fit.predict_proba(test)
        print '[s='+str(s)+' cs='+str(cs)+' ] '+str(cross_validation.cross_val_score(clf, data, target, scoring='log_loss'))

In [ ]:
for n in range(100, 450, 25):
    for d in range (2, 11, 1):
        for s in np.arange(0,1,0.1):
            for cs in np.arange(0,1,0.1):
                clf = xgb.XGBClassifier(max_depth=d, n_estimators=n, learning_rate=0.05, silent=1, objective='multi:softprob',
                        subsample=s,colsample_bytree=cs)
                fit = clf.fit(data, target)
                proba = fit.predict_proba(test)
                print '[n='+str(n)+' d='+str(d)+' s='+str(s)+' cs='+str(cs)+' ] '+str(cross_validation.cross_val_score(clf, data, target, scoring='log_loss'))

<hr />
Salvando em arquivo CSV para enviar ao Kaggle

In [85]:
#proba = fit.predict_proba(test)
ret = pd.DataFrame(proba, index=test.index, columns=fit.classes_)
#ret.index = ret.index+1
ret.sort_index(inplace=True)
ret.to_csv('output/submission.csv', index_label="ID")

In [51]:
cross_validation.cross_val_score(clf, data, target, scoring='log_loss') 

array([-0.72758765, -0.72300306, -0.71813888])

[-0.7252497  -0.72362816 -0.71610143]

array([-0.72645001, -0.72301075, -0.71964613])

array([-0.72873917, -0.72380463, -0.72159486])

array([-0.74041248, -0.73777135, -0.72835238])

array([-0.73664086, -0.73223007, -0.72688397]) - 250 todas novas features

array([-0.73662436, -0.73447814, -0.72777039]) - 250 novas features com breed (somente size e grupo)

array([-0.73897436, -0.73514682, -0.72964329]) - 250 novas features (sem breed)

array([-0.74055679, -0.73587788, -0.72771282]) 250

array([-0.74086091, -0.73629684, -0.72751988]) 300

array([-0.74145022, -0.73730085, -0.72769767]) 325

array([-0.73915104, -0.73577702, -0.72817969])

array([-0.74346893, -0.73752276, -0.72980024])

array([-0.74321041, -0.73832364, -0.73052855])

array([-0.74873247, -0.74552813, -0.73572743])

array([-0.75646983, -0.74827674, -0.74707565])

array([-0.75622374, -0.75086099, -0.74849421])

array([-0.75715345, -0.75192073, -0.74662878]) - estimators = 325

array([-0.75753229, -0.75203215, -0.74645084]) - estimators = 350

array([-0.75726917, -0.75237363, -0.74653154]) - depth = 6

array([-0.76324843, -0.75360441, -0.74913675])

array([-0.76832682, -0.76022552, -0.75612068])

array([-0.77868186, -0.76961524, -0.7654266 ])

array([-0.80053641, -0.79496805, -0.79203674])

array([-0.87241774, -0.86908006, -0.85758873])

array([-0.90137227, -0.89607375, -0.89042396])


**Fim** <br />
Esse notebook é um exemplo mais simples que podemos fazer o uso do Machine Learning com a bibioteca Python + Sklearn. <br /><br />
Existem algumas evolutivas que podem ser feitas para uma melhor performance:
- adicionar novas features
- fazer uso cross-validation para fazer testes
- fazer o uso de ensembling para melhorar o seu score no final
- Testar com diferentes parâmetros no seu método.
- Etc...

O próximo notebook criarei um exemplo usando o Cross-Validation e criando novas features.

In [41]:
clf = xgb.XGBClassifier(max_depth=6, n_estimators=325, learning_rate=0.05, silent=1, objective='multi:softprob',
                        subsample=0.55,colsample_bytree=0.65)
fit = clf.fit(data, target)
proba = fit.predict_proba(test)
cross_validation.cross_val_score(clf, data, target, scoring='log_loss') 

KeyboardInterrupt: 

In [ ]:
clf = RandomForestClassifier(n_estimators=200)
fit = clf.fit(data, target)
proba = fit.predict_proba(test)
cross_validation.cross_val_score(clf, data, target, scoring='log_loss') 

In [275]:
ret = pd.DataFrame(proba, index=test.index, columns=fit.classes_)
ret.sort_index(inplace=True)
ret.to_csv('output/submission.csv', index_label="ID")